cache:
  paths:
    - target/

stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test
    
test-sonar:
  stage: test
  script:
    - mvn --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar -Dsonar.projectKey=GitlabDeveloper_knowledgestore-back -Dsonar.organization=gitlabdeveloper-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=ca7e268987fb4b31c1dfaa34aaa1107733119c9b
    
deploy_prod:
  stage: deploy
  script:
    - mvn deploy
  only:
    - master