before-script:
  mvn --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar -Dsonar.projectKey=AlexeyRadkevich_knowledgestore-back -Dsonar.organization=alexeyradkevich-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=e5e00947f52ecf2ed65dd4ac886307fcfd897f19
cache:
  paths:
    - target/

stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - mvn compile
  artifacts:
    paths:
      - target/knowledgestore-back.jar

test:
  stage: test
  script:
    - mvn test
    
deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: http://tracker.eklib.com
  when: manual
  only:
  - master