cache:
  paths:
    - target/

stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - mvn compile
  artifacts:
    paths:
      - target/knowledgestore-back.jar

test:
  stage: test
  script:
    - mvn test
    
deploy_prod:
  stage: deploy
  environment:
    name: production
    url: http://tracker.eklib.com
  when: manual
  only:
  - master