INSERT IGNORE INTO role (id, name) VALUES (1, 'ROLE_USER!');
INSERT IGNORE INTO role (id, name) VALUES (2, 'ROLE_ADMIN');
INSERT IGNORE INTO role (id, name) VALUES (3, 'ROLE_TEACHER');
INSERT IGNORE INTO role (id, name) VALUES (4, 'ROLE_STUDENT');